
DATA SEGMENT        
T0 EQU 280H
T1 EQU 281H
CTL53 EQU 283H
PA EQU 288H
PB EQU 289H
PC EQU 28AH
CTL55 EQU 28BH
DATA ENDS

STACK1 SEGMENT PARA STACK
   DW 20 DUP(0)
STACK1 ENDS
COSEG SEGMENT
  ASSUME CS:COSEG,DS:DATA,SS:STACK1
START:MOV AX,DATA
      MOV DS,AX
      MOV CX,200H
      
      MOV DX,CTL53
      MOV AL,00110111B
      OUT DX,AL

      MOV DX,T0
      MOV AL,00H
      OUT DX,AL
      MOV AL,10H
      OUT DX,AL

      MOV DX,T1
      MOV AL,10H
      OUT DX,AL
      MOV AL,00H
      OUT DX,AL

WAT: MOV DX,PC
      IN AL,DX
      AND AL,80H
      JNZ WAT

NEXT1: MOV AL,00H

NEXT2:  MOV DX,290H ;290作为0832片选接入地址
        OUT DX,AL
        CALL DELAY
    CMP AL,80H
    JZ NEXT3
    ADD AL,10H
    JMP NEXT2
NEXT3:  LOOP NEXT1
    MOV AH,4CH
    INT 21H      

DELAY PROC NEAR
      PUSH AX
WAT1: MOV DX,PC
      IN AL,DX
      AND AL,80H
      JNZ WAT1
WAT2: MOV DX,PC
      IN AL,DX
      AND AL,80H
      JZ WAT2  
      POP AX
      RET
DELAY ENDP
COSEG ENDS
END START