
DATA SEGMENT
DATA ENDS
STACK1 SEGMENT PARA STACK
       DW 20H DUP(0)
STACK1 ENDS
COSEG SEGMENT
      ASSUME CS:COSEG,DS:DATA,SS:STACK1
START:MOV AX,DATA
      MOV DS,AX
      MOV CX,200H
NEXT1:MOV AL,00H

NEXT4:MOV DX,280H
      OUT DX,AL
      CALL DELAY
      CMP AL,0FfH
      JZ NEXT5
      ADD AL,10H
      JMP NEXT4

NEXT5:LOOP NEXT1
      MOV AH,4CH
      INT 21H

DELAY PROC NEAR
      PUSH CX
      MOV CX,0FFFH
NEXT2:LOOP NEXT2
      MOV CX,0FFFH
NEXT3:LOOP NEXT3
      POP CX
      RET
DELAY ENDP
COSEG ENDS
      END START